"""Lol2

Revision ID: 8d87b654254e
Revises: 750391b08ceb
Create Date: 2026-01-18 23:43:13.984491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d87b654254e'
down_revision: Union[str, Sequence[str], None] = '750391b08ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('has_comments', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('workers')
    # op.drop_table('devisions')
    # op.drop_table('organize')
    # op.drop_table('positions')
    # op.drop_table('workingcalendar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workingcalendar',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exceptiondate', sa.DATE(), autoincrement=False, nullable=False, comment='День-исключение'),
    sa.Column('isworkingday', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='0 - будний день, но законодательно принят выходным; 1 - сб или вс, но является рабочим'),
    sa.PrimaryKeyConstraint('id', name=op.f('workingcalendar_pk')),
    comment='Список дней исключений в производственном календаре'
    )
    op.create_table('positions',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('positions_pkey')),
    sa.UniqueConstraint('name', name=op.f('positions_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('organize',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('organize_pkey'))
    )
    op.create_table('devisions',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('organize_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organize_id'], ['organize.id'], name=op.f('devisions_organize_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('devisions_pkey'))
    )
    op.create_table('workers',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('surname', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('middle_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('devision_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cabinet', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['devision_id'], ['devisions.id'], name=op.f('workers_devision_id_fkey')),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('workers_position_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('workers_pkey'))
    )
    op.drop_table('comments')
    op.drop_table('documents')
    # ### end Alembic commands ###
